spring:
  application:
    name: springTemplate
  thymeleaf:
    cache: false
    enabled: true
    prefix: 'classpath:/templates/'
    suffix: '.html'
  datasource:
    url: jdbc:postgresql://database-postgres:5432/books
    username: booksUser
    password: booksPass
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl : true

server:
  port: 80

