spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: 'classpath:/templates/'
    suffix: '.html'
  application:
    name: springTemplate
  datasource:
    url: jdbc:h2:mem:bookDatabase
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 9123

